### ISSUE TITLE
[Feature] Embed

### ISSUE THREAD

**Issue by xNaCly** [fosscord/fosscord-ui#25]
![image](https://user-images.githubusercontent.com/47723417/115972301-d2a49b80-a54d-11eb-9eab-f5c3cde946df.png)
- useravatar
- date (time)
- name
- Bot badge
- left border custom color
- all fields

**Comment by xNaCly** [comment]
![image](https://user-images.githubusercontent.com/47723417/116215724-3abed180-a748-11eb-9356-9feb6eb55bf6.png)
Current progess

**Comment by Flam3rboy** [comment]
I think everything looks correct 👍 maybe just change the time format to ``new Date().toLocaleString()``?

**Comment by xNaCly** [comment]
Its just a placeholder, the content depends on the User
