### ISSUE TITLE
[Question] License

### ISSUE THREAD

**Issue by Latrolage** [fosscord/fosscord-ui#27]
I assume that all the fosscord repositories are modular and are put together in the final client? (the server is separate obviously)

But why the discrepancy in licenses? (MIT and GPLv3)

**Comment by xNaCly** [comment]
This is due to us the current maintainers voting on that the server is not allowed to be used commercially but everything else is.

**Comment by Latrolage** [comment]
Ok, sorry I specifically mean why use 2 different open source licenses, MIT and GPL. (unless you already answered that, but both of these licenses allow commercial use so I think you answered something else)

**Comment by xNaCly** [comment]
Oh youre right, that must be an error on my side, im gonna have to talk to the others ob that one

**Comment by Latrolage** [comment]
Ok i didn't click on read licenses but it looks like the the "fosscord-client" repository is again yet another open source license called "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License"

**Comment by xNaCly** [comment]
Yeah we gotta clean that up, its a real mess. I'm gonna talk to the others and we will fix the issues with the licenses.

**Comment by Flam3rboy** [comment]
so this repository should be MIT license for e.g. bot developers to use this framework for their dashboard and not make everything open source

**Comment by Flam3rboy** [comment]
generally we use GPL, fosscord-themes will just be a collection of offical fosscord client themes

**Comment by Flam3rboy** [comment]
The server will be Creative Commons NonCommercial license, but we are not yet sure about the client.

**Comment by asdfugil** [comment]
that said "NonCommercial` will make the software not "free"
Still open source but not free.

**Comment by Flam3rboy** [comment]
yeah sorry about the confusing name, you could say it’s free (Price) or fair 🙈

**Comment by Flam3rboy** [comment]
we'll choose AGPL for the client, and "Creative Commons Non Commercial" for the server

**Comment by Flam3rboy** [comment]
everything is now licensed under GPL V3
except for [fosscord-ui](https://github.com/fosscord/fosscord-ui/issues/27), it is licensed under MIT for e.g. bot dashboards
