### ISSUE TITLE
[Feature] Tooltip

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord-ui#3]
- [x] open with animation
- [x] multiple colors

should look like
![image](https://user-images.githubusercontent.com/34555296/103575592-3ee18d80-4ed2-11eb-80be-40c56c8135e0.png)
![image](https://user-images.githubusercontent.com/34555296/103576829-0c389480-4ed4-11eb-8e80-c32df0aad010.png)

**Comment by Stefan080106** [comment]
I made a first version of a tooltip, but the style is not good.
The tooltip must be recentered.

**Comment by xNaCly** [comment]
Doesn't work on IOS-mobile.
(iPhone 12 mini, safari - IOS 14.5.1)

**Comment by HugoHead** [comment]
What specifically needs to be changed about the tooltip? The margins have rather ugly proportions, but that is an easy fix. What else?

**Comment by Flam3rboy** [comment]
fixed
