### ISSUE TITLE
[Feature] Popup

### ISSUE THREAD

**Issue by Flam3rboy** [fosscord/fosscord-ui#7]
should look like:
![image](https://user-images.githubusercontent.com/34555296/103578033-2a06f900-4ed6-11eb-8163-9e020df03a36.png)

just use a list with other hover color
![image](https://user-images.githubusercontent.com/34555296/103578127-4e62d580-4ed6-11eb-9c3b-6f3683b0e1b7.png)

**Comment by BuilderHD** [comment]
Lets do it!

**Comment by Stefan080106** [comment]
Fix popup error and make it functional

<hr/>

![image](https://user-images.githubusercontent.com/53957363/116826784-04dd7b00-ab96-11eb-9ec9-e5299d53195c.png)

**Comment by Flam3rboy** [comment]
Does it work on mobile?

**Comment by ThatOneCalculator** [comment]
> Does it work on mobile?

Nope, not for me lol

**Comment by Stefan080106** [comment]
> Does it work on mobile?

I haven't tested it on mobile, but after the last feedback I will do it

**Comment by Stefan080106** [comment]
I have made the mobile popup

<hr/>

![image](https://user-images.githubusercontent.com/53957363/116903700-09a93a00-ac3d-11eb-90df-737f436e9cc5.png)
